---
- hosts: command
  remote_user: root
  
  tasks:
    - name: set up user account
      user:
        name: lotus
        comment: "Lotus User"
        groups: sudo
        shell: /bin/bash
        
    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
  
    - name: install required packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible
        - aptitude
        - curl
        - git
        - python
        - python-pip
        - software-properties-common
        - unzip
    
    - name: install required pip packages
      pip:
        name:
          - requests
        state: latest

    - name: copy dynamic hosts file
      copy:
        src: /root/lotus/dynamic_hosts/dynamic_hosts_scripts/dynamic_hosts.py
        dest: /etc/ansible/dynamic_hosts.py
        owner: root
        group: root
        mode: 0755

    - name: copy Ansible config file
      copy:
        src: /root/lotus/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        owner: root
        group: root
        mode: 0755
        backup: yes
    
    - name: remove bootstrap cron.d job
      file:
        path: /etc/cron.d/cron_bootstrap
        state: absent
    
    - name: set up command playbook cron job
      cron:
        name: "Run command playbook"
        minute: "*/5"
        state: present
        job: "ansible-playbook /lotus/command-server.yml"
    
    # Munki server cron job
    - name: set up munki playbook cron job
      cron:
        name: "Run munki playbook"
        minute: "*/10"
        state: present
        job: "ansible-playbook /lotus/munki.yml"
    
    # MunkiReport server cron job
    - name: set up munkireport playbook cron job
      cron:
        name: "Run munkireport playbook"
        minute: "*/10"
        state: present
        job: "ansible-playbook /lotus/munkireport.yml"
