---
- hosts: munki
  remote_user: root
  vars:
    # Should by dynamically generated
    munki_nginx_fqdn: 8.8.8.8
  
  tasks:
    - name: create munki group
      group:
        name: munki
        system: yes
    
    - name: create munki user
      user:
        name: munki
        comment: "Munki User"
        group: munki
        shell: /bin/bash
        system: yes
    
    - name: add www-data (web user) to munki group
      user:
        name: www-data
        group: munki

    - name: create munki repo
      file:
        path: "/usr/local/munki_repo/{{item}}"
        state: directory
        owner: root
        group: munki
        mode: 02744
        recurse: yes
      with_items:
        -
        - catalogs
        - client_resources
        - icons
        - manifests
        - pkgs
        - pkgsinfo
    
    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: install requred packages
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - python
        - git
        - curl
        - build-essential
        - nginx
        - apache2-utils
    
    # FIX THIS
    - name: apply nginx sites-available template
      template:
        src: munki_sites-available_default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644
        backup: yes
    
    -
    
    
    
    
    
