---
- hosts: munkireport
  remote_user: root
  vars:
    mysql_root_password: abc123
  
  tasks:
    - user:
        name: munkireport
        comment: "MunkiReport User"
        shell: /bin/bash
        system: yes
        
    - apt:
        update_cache: yes
        upgrade: yes
  
    - apt:
        name: "{{item}}"
        state: latest
      with_items:
        - python
        - git
        - curl
        - nginx
        - php7.0-fpm
        - php7.0-mysql
        - php7.0-xml
        - mysql-client
        - mysql-server
        - python-mysqldb
    
    - template:
        src: mysql_root_credentials
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0644
        backup: yes
        
    - mysql_user:
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost
    
    - mysql_user:
        name: ''
        state: absent
    
    - mysql_db:
        db: test
        state: absent
    
    - mysql_db:
        db: munkireport
        state: present
        encoding: utf8
        collation: utf8_bin
    
    - mysql_user:
        name: munkireport_user
        password: 12345
        encrypted: no
        priv: 'munkireport.*:ALL,GRANT'
        state: present
    
    - lineinfile:
        path: /etc/php/7.0/fpm/php.ini
        regexp: '.*cgi.fix_pathinfo='
        line: 'cgi.fix_pathinfo=0'
    
    - git:
        repo: 'https://github.com/munkireport/munkireport-php'
        dest: /usr/share/nginx/html/report
        clone: yes
        update: yes
    
    - template:
        src: munkireport_config.php
        dest: /usr/share/nginx/html/report/config.php
        owner: root
        group: root
        mode: 0644
    
    - template:
        src: munkireport_sites-available_default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644
        backup: yes
    
    - lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '.*default_type application/octet-stream;'
        line: '#default_type application/octet-stream;'
    
    
    
    
    
    
    
    
    
    
    
    
    
