---
- hosts: munkireport
  remote_user: root
  
  tasks:
    - name: create munkireport user
      user:
        name: munkireport
        comment: "MunkiReport User"
        shell: /bin/bash
        system: yes
        
    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
  
    - name: install required packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - aptitude
        - curl
        - git
        - mysql-client
        - mysql-server
        - nginx
        - php7.0-fpm
        - php7.0-mysql
        - php7.0-xml
        - python
        - python-mysqldb
    
    - name: create mysql root credentials
      template:
        src: /root/lotus/templates/munkireport_mysql_credentials
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600
        backup: yes
        
    - name: create mysql root user
      mysql_user:
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost
    
    - name: remove anonymous mysql users
      mysql_user:
        name: ''
        state: absent
    
    - name: remove mysql test database
      mysql_db:
        db: test
        state: absent
    
    - name: create munkireport mysql database
      mysql_db:
        db: munkireport
        state: present
        encoding: utf8
        collation: utf8_bin
    
    - name: create munkireport mysql user
      mysql_user:
        name: mysql_munkireport_user
        password: "{{ mysql_munkireport_password }}"
        priv: 'munkireport.*:ALL,GRANT'
        state: present
    
    - name: modify php settings
      lineinfile:
        path: /etc/php/7.0/fpm/php.ini
        regexp: '.*cgi.fix_pathinfo='
        line: 'cgi.fix_pathinfo=0'
      notify:
        - restart nginx
        - restart php
    
    - name: clone munkireport github repo
      git:
        repo: 'https://github.com/munkireport/munkireport-php.git'
        dest: /usr/share/nginx/html/munkireport
        clone: yes
        update: yes
      notify:
        - restart nginx
        - restart php
    
    - name: create munkireport config.php file
      template:
        src: /root/lotus/templates/munkireport_config.php
        dest: /usr/share/nginx/html/report/config.php
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx
        - restart php
    
    - name: apply nginx sites-available template
      template:
        src: /root/lotus/templates/munkireport_sites-available
        dest: /etc/nginx/sites-available/munkireport
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
        - restart nginx

    - name: remove default from nginx sites-enabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx
        - restart php
    
    - name: add munkireport to nginx sites-enabled
      file:
        src: /etc/nginx/sites-available/munkireport
        dest: /etc/nginx/sites-enabled/munkireport
        state: link
      notify:
        - restart nginx
        - restart php
    
    - name: modify nginx config file
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '.*default_type application/octet-stream;'
        line: '#default_type application/octet-stream;'
      notify:
        - restart nginx
    
    - name: ensure web services are running
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - nginx
        - php7.0-fpm
        
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    
    - name: restart php
      service:
        name: php7.0-fpm
        state: restarted
