---
- hosts: munki
  remote_user: root
  
  tasks:
    - name: create munki group
      group:
        name: munki
        system: yes
    
    - name: create munki user
      user:
        name: munki
        comment: "Munki User"
        group: munki
        shell: /bin/bash
        system: yes
    
    - name: add web user (www-data) to munki group
      user:
        name: www-data
        group: munki

    - name: create munki repo
      file:
        path: "/usr/local/munki_repo/{{ item }}"
        state: directory
        owner: root
        group: munki
        mode: 02744
        recurse: yes
      with_items:
        -
        - catalogs
        - client_resources
        - icons
        - manifests
        - pkgs
        - pkgsinfo
    
    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: install required packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - apache2-utils
        - aptitude
        - build-essential
        - curl
        - git
        - nginx
        - python
    
    - name: apply nginx sites-available template
      template:
        src: /root/lotus/templates/munki/munki_sites-available_default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
        - restart nginx
    
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
        
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
