---
- hosts: command
  remote_user: root
  #vars:
      #lotus_user_name: johndoe
      # Used for testing
      #dynamic_hosts_script = digitalocean_dynamic_hosts.py
  
  tasks:
    - name: set up user account
      user:
        name: "{{ lotus_user_name }}"
        #comment: ""
        groups: sudo
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa
        
    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
  
    - name: install required packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible
        - aptitude
        - curl
        - git
        - python
        - python-pip
    
    - name: install required pip packages
      pip:
        name:
          - requests
        state: latest
    
    - name: clone lotus github repo
      git:
        repo: 'https://github.com/jacobfgrant/lotus.git'
        dest: /root/lotus/
        clone: yes
        update: yes

    - name: copy dynamic hosts file
      copy:
        src: "/root/lotus/dynamic_hosts/dynamic_hosts_scripts/{{ dynamic_hosts_script }}"
        dest: /etc/ansible/dynamic_hosts.py
        owner: root
        group: root
        mode: 0755
