---
- hosts: localhost
  remote_user: root
  
  tasks:
    - name:
      user:
        name: {{ lotus_user_name }}
        #comment: ""
        groups: sudo
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa
        
    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
  
    - name: install requred packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible
        - aptitude
        - curl
        - git
        - python
    
    - name: clone munkireport github repo
      git:
        repo: 'https://github.com/jacobfgrant/lotus.git'
        dest: /root/lotus/
        clone: yes
        update: yes

    - name: copy dynamic hosts file
      copy:
        src: /root/lotus/dynamic_hosts/dynamic_hosts/{{ dynamic_hosts_script }}
        dest: /etc/ansible/dynamic_hosts.py
        owner: root
        group: root
        mode: 0755
