---
- hosts: localhost
  remote_user: root
  
  tasks:
    - name:
      user:
        name:
        comment: ""
        group:
        shell: /bin/bash
        system:
            
    - name:
      user:
        name:
        comment: ""
        group:
        shell: /bin/bash
        system:

    - name:
      file:
        path: /etc/ansible/hosts
        state: file
        owner: root
        group: root
        mode: 0644

    - name:
      file:
        path: "/etc/ansible/{{item}}"
        state: file
        owner: root
        group: root
        mode: 0644
        recurse: yes
      with_items:
        - hosts
        - client_resources
        - icons
        - manifests
        - pkgs
        - pkgsinfo
    
    - name: clone munkireport github repo
      git:
        repo: 'https://github.com/jacobfgrant/lotus.git'
        dest: /root/lotus/
        clone: yes
        update: yes
