# Command tasks
---
- name: set up user account
  user:
    name: lotus
    comment: "Lotus User"
    groups: sudo
    shell: /bin/bash
    
- name: update/upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install required packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - python-pip
    - software-properties-common
    - unzip

- name: install required pip packages
  pip:
    name:
      - requests
    state: latest

- name: copy Ansible files
  copy:
    src: /root/lotus/ansible/
    dest: /etc/ansible/
    owner: root
    group: root
    mode: 0744
    backup: yes

- name: remove bootstrap cron.d job
  file:
    path: /etc/cron.d/cron_bootstrap
    state: absent

- name: set up command playbook cron job
  cron:
    name: "Run command playbook"
    minute: "*/5"
    state: present
    job: "ansible-playbook /etc/ansible/command.yml >> /var/log/lotus/command.log 2>&1"

# Munki server cron job
- name: set up munki playbook cron job
  cron:
    name: "Run munki playbook"
    minute: "*/10"
    state: present
    job: "ansible-playbook /etc/ansible/munki.yml >> /var/log/lotus/munki.log 2>&1"

# MunkiReport server cron job
- name: set up munkireport playbook cron job
  cron:
    name: "Run munkireport playbook"
    minute: "*/10"
    state: present
    job: "ansible-playbook /etc/ansible/munkireport.yml >> /var/log/lotus/munkireport.log 2>&1"
